#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render two proposed G2.2 families at controlled engraving scales.

No new symbol is standard, final or accepted. Inputs must be generated by
build_lilypond_g22.py from a legitimate GNU LilyPond Emmentaler font.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from build_lilypond_g22 import CATALOGUE, DENOMINATORS

COLORS={"ink":"#302827","bg":"#F5F1E9","card":"#FFFFFF",
        "line":"#C7BEB4","muted":"#72675E","gold":"#8D663E",
        "warn":"#A24E3B"}

GLYPHS={g.key:g for g in CATALOGUE}
LABELS={"twelfth":"1/12 de tono","eighth":"1/8 de tono",
        "sixth":"1/6 de tono","three_eighths":"3/8 de tono"}


def font_ui(size:int):
    for path in ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
                 "/System/Library/Fonts/Supplemental/Arial.ttf"]:
        try:
            return ImageFont.truetype(path,size)
        except OSError:
            continue
    return ImageFont.load_default()


def staff(draw,x1,x2,cy,step,width=1):
    for i in range(-2,3):
        y=int(cy+i*step)
        draw.line((x1,y,x2,y),fill=COLORS["line"],width=width)


def notehead(d,x,y,size=9):
    d.ellipse((x-size,y-size*.6,x+size,y+size*.6),fill=COLORS["ink"])
    d.line((x+size,y,x+size,y-size*4),fill=COLORS["ink"],width=2)


def text(d,x,y,what,size=16,color="ink"):
    d.text((x,y),str(what),font=font_ui(size),fill=COLORS[color])


def stamp(d,fontpath,code,px,baseline,size):
    face=ImageFont.truetype(str(fontpath),int(size))
    d.text((px,baseline),chr(code),font=face,fill=COLORS["ink"],anchor="ls")


def family_preview(fontpath:Path,metadata:dict,mode:str,target:Path):
    if mode not in ("A","B"):
        raise ValueError("A or B required")
    W,H=1250,1595
    im=Image.new("RGB",(W,H),COLORS["bg"])
    d=ImageDraw.Draw(im)
    text(d,37,26,"ESFERAS MICROTONAL · G2.2",35)
    text(d,38,82,"FAMILIA "+mode+" · "+
         ("rayas finas auxiliares" if mode=="A" else "terminales abiertos en horquilla"),
         21,"gold")
    text(d,38,122,
         "Ocho candidatos NO aprobados. Base Emmentaler / GNU LilyPond; nuevas marcas ligeras.",
         16,"muted")
    text(d,38,150,
         "Un tono = 200 cents; códigos privados solo de estudio, no símbolos SMuFL.",
         15,"warn")
    xx=(38,641)
    names=[("twelfth","down"),("twelfth","up"),
           ("eighth","down"),("eighth","up"),
           ("sixth","down"),("sixth","up"),
           ("three_eighths","down"),("three_eighths","up")]
    for j,(fraction,direction) in enumerate(names):
        row,col=divmod(j,2)
        x,y=xx[col],209+row*325
        w,h=565,312
        d.rounded_rectangle((x,y,x+w,y+h),radius=13,fill=COLORS["card"],
                            outline=COLORS["line"],width=2)
        spec=GLYPHS[f"{mode.lower()}_{fraction}_{direction}"]
        value=metadata["glyphs"][spec.key]["exact_cents"]
        sign="+" if value["numerator"]>0 else "−"
        value_display=abs(value["numerator"])
        if value["denominator"]>1:
            value_display=f"{value_display}/{value['denominator']}"
        text(d,x+16,y+13,
             f"{LABELS[fraction]} · {'descendente' if direction=='down' else 'ascendente'}",
             19)
        text(d,x+16,y+49,
             f"{sign}{value_display} cents  ·  U+{spec.codepoint:04X}",
             16,"gold")
        # Macro reference and 2 full staff-size specimens.
        stamp(d,fontpath,spec.codepoint,x+133,y+186,153)
        text(d,x+12,y+202,"s = 12 px",14,"muted")
        cy=y+256
        staff(d,x+83,x+322,cy,12)
        stamp(d,fontpath,spec.codepoint,x+130,cy,50)
        notehead(d,x+262,cy,8)
        text(d,x+360,y+212,"s = 7 px",14,"muted")
        staff(d,x+358,x+539,cy,7)
        stamp(d,fontpath,spec.codepoint,x+383,cy,30)
        notehead(d,x+501,cy,6)
    text(d,40,H-69,
         "Comparación de diseño. El valor musical no se deduce del número de trazos.",
         17,"muted")
    text(d,40,H-37,
         "Revisión humana obligatoria: s=7 px, legibilidad, colisiones e identidad histórica.",
         16,"warn")
    target.parent.mkdir(parents=True,exist_ok=True)
    im.save(target)
    print("G2.2 family:",mode,target,im.size)


def index_preview(fontpath:Path,metadata:dict,target:Path):
    W,H=1830,1085
    im=Image.new("RGB",(W,H),COLORS["bg"])
    d=ImageDraw.Draw(im)
    text(d,30,25,"G2.2 · Comparación directa de dos gramáticas",31)
    text(d,31,76,
         "Contornos base: LilyPond. Signos de fracción: NUEVOS y sin aprobación.",
         18,"muted")
    headings=["A: hacia abajo","A: hacia arriba",
              "B: hacia abajo","B: hacia arriba"]
    for i,h in enumerate(headings):
        text(d,199+i*403,126,h,18,"gold")
    for row,(fraction,p,q) in enumerate(DENOMINATORS):
        y=174+row*211
        text(d,24,y+15,LABELS[fraction],20)
        text(d,24,y+52,f"± {200*p/q:g} cents",16,"muted")
        for col,(mode,direction) in enumerate([
            ("A","down"),("A","up"),("B","down"),("B","up")
        ]):
            x=191+col*403
            d.rounded_rectangle((x,y,x+387,y+181),radius=9,
                                fill=COLORS["card"],outline=COLORS["line"])
            spec=GLYPHS[f"{mode.lower()}_{fraction}_{direction}"]
            midx=x+150
            stamp(d,fontpath,spec.codepoint,midx,y+116,102)
            staff(d,x+46,x+354,y+145,9)
            text(d,x+9,y+12,f"U+{spec.codepoint:04X}",13,"muted")
    text(d,30,1037,
         "Ver las láminas A/B para comprobar la lectura a s=7 y 12 px.",
         17,"warn")
    target.parent.mkdir(parents=True,exist_ok=True)
    im.save(target)
    print("G2.2 comparison:",target,im.size)


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument("--font",required=True)
    parser.add_argument("--outdir",required=True)
    args=parser.parse_args()
    path=Path(args.font)
    metadata=json.loads(path.with_suffix(".json").read_text(encoding="utf8"))
    if metadata["approved"]:
        raise ValueError("G2.2 must remain candidates")
    directory=Path(args.outdir)
    for mode in ("A","B"):
        family_preview(path,metadata,mode,directory/f"esferas-g22-{mode.lower()}.png")
    index_preview(path,metadata,directory/"esferas-g22-comparacion.png")


if __name__=="__main__":
    main()
